sudo: false
language: python
python:
  - "3.5"
dist: trusty
env:
  global:
    - PYTEST_ADDOPTS="-n 3"
  matrix:
    # TODO: py27
    # TODO: py34
    - TOX_POSARGS="-e py35-blockchain-frontier"
    - TOX_POSARGS="-e py35-blockchain-homestead"
    - TOX_POSARGS="-e py35-blockchain-eip150"
    #- TOX_POSARGS="-e py35-blockchain-eip158"
    #- TOX_POSARGS="-e py35-blockchain-metropolis"
    - TOX_POSARGS="-e py35-state-frontier"
    - TOX_POSARGS="-e py35-state-homestead"
    - TOX_POSARGS="-e py35-state-eip150"
    #- TOX_POSARGS="-e py35-state-eip158"
    #- TOX_POSARGS="-e py35-state-byzantium"
    #- TOX_POSARGS="-e py35-state-constantinople"
    #- TOX_POSARGS="-e py35-state-metropolis"
    - TOX_POSARGS="-e py35-vm"
    - TOX_POSARGS="-e py35-core"
    - TOX_POSARGS="-e py35-transactions"
    - TOX_POSARGS="-e py35-p2p"
    - TOX_POSARGS="-e py35-database"
    #- TOX_POSARGS="-e py35-vm-performance"
    - TOX_POSARGS="-e flake8"
cache:
  pip: true
install:
  - "travis_retry pip install pip setuptools --upgrade"
  - "travis_retry pip install tox"
before_script:
  - pip freeze
script:
  - tox $TOX_POSARGS
after_script:
  - cat .tox/$TOX_POSARGS/log/*.log
