sudo: false
language: python
python:
  - "3.5"
dist: trusty
env:
  global:
    - PYTEST_ADDOPTS="-n 3"
  matrix:
    # TODO: py27
    # TODO: py34
    - TOX_POSARGS="-e py35-blockchain-fast"
    - TOX_POSARGS="-e py35-blockchain-slow"
    - TOX_POSARGS="-e py35-core"
    - TOX_POSARGS="-e py35-state-fast"
    - TOX_POSARGS="-e py35-state-slow"
    - TOX_POSARGS="-e py35-transactions"
    - TOX_POSARGS="-e py35-vm-fast"
    - TOX_POSARGS="-e py35-vm-limits"
    - TOX_POSARGS="-e py35-coincurve"
    - TOX_POSARGS="-e py35-leveldb"
    #- TOX_POSARGS="-e py35-vm-performance"
    - TOX_POSARGS="-e flake8"
cache:
  pip: true
install:
  - "travis_retry pip install pip setuptools --upgrade"
  - "travis_retry pip install tox"
before_script:
  - pip freeze
script:
  - tox $TOX_POSARGS
after_script:
  - cat .tox/$TOX_POSARGS/log/*.log
