sudo: false
language: python
python:
  - "3.5"
dist: trusty
env:
  matrix:
    #- TOX_ENV=py27
    #- TOX_ENV=py34
    - TOX_ENV=py35-blockchain
    - TOX_ENV=py35-core
    - TOX_ENV=py35-state
    - TOX_ENV=py35-transactions
    - TOX_ENV=py35-vm
    - TOX_ENV=flake8
cache:
  pip: true
install:
  - "travis_retry pip install pip setuptools --upgrade"
  - "travis_retry pip install tox"
before_script:
  - pip freeze
script:
  - tox -e $TOX_ENV --recreate
after_script:
  - cat .tox/$TOX_ENV/log/*.log
